version: "3"  

tasks:  
  default: # Если не указать конкретную команду, будут выполнены дефолтные
    cmds:  
      - task: generate  
  generate:  ## Команда для генерации
    aliases: ## Алиасы команды, для простоты использования
      - gen  
    desc: "Generate code from proto files"  
    dir: ./
    cmds:  ## Тут описываем необходимые bash-команды
      - protoc *.proto --go_out=../auth/proto --go_opt=paths=source_relative --go-grpc_out=../auth/proto  --go-grpc_opt=paths=source_relative
      - protoc *.proto --go_out=../log_storage/proto --go_opt=paths=source_relative --go-grpc_out=../log_storage/proto  --go-grpc_opt=paths=source_relative
      - protoc *.proto --go_out=../log_storage/tests/serialized_test/proto --go_opt=paths=source_relative --go-grpc_out=../log_storage/tests/serialized_test/proto  --go-grpc_opt=paths=source_relative
      - protoc *.proto --go_out=../windows_agent/proto --go_opt=paths=source_relative --go-grpc_out=../windows_agent/proto  --go-grpc_opt=paths=source_relative
      - protoc *.proto --go_out=../log_analyze --go_opt=paths=source_relative --go-grpc_out=../log_analyze/proto  --go-grpc_opt=paths=source_relative


