name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install protoc and Go plugins
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: Create build directory
      run: mkdir -p build

    - name: Generate Protobuf files
      run: |
        export PATH="$PATH:$(go env GOPATH)/bin"
        protoc -I=./proto --go_out=./log_storage/proto --go-grpc_out=./log_storage/proto ./proto/*.proto

    - name: Copy config file
      run: cp ./log_storage/server-config.yaml build/

    # Сборка приложения
    - name: Build
      run: go build -v -o build/log-storage ./log_storage/cmd/server/main.go